sudo: required
service:
  - docker

before_install:
  - docker image build -t brightshark/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run -e CI=true brightshark/react-test npm test

after_success:
  # Build images
  - docker image build -t brightshark/multi-client ./client
  - docker image build -t brightshark/multi-nginx ./nginx
  - docker image build -t brightshark/multi-server ./server
  - docker image build -t brightshark/multi-worker ./worker

  # Log into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub registry
  - docker image push brightshark/multi-client
  - docker image push brightshark/multi-nginx
  - docker image push brightshark/multi-server
  - docker image push brightshark/multi-worker
